"""
Django settings for rednote_project project.

Generated by 'django-admin startproject' using Django 4.2.26.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(6tgyristp*pg!z55$amim#6$v4&l@eqnjhy#$2rghf87b&8km'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'jazzmin',  # Professional Admin Theme
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',  # Django REST Framework
    'corsheaders',  # CORS headers
    'downloader',  # RedNote downloader app
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS middleware - must be before CommonMiddleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Note: The unload permissions policy violation warning from Django admin's RelatedObjectLookups.js
# is a harmless browser warning and doesn't affect functionality. It's suppressed via meta tag in templates.

ROOT_URLCONF = 'rednote_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'rednote_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Media files (Videos, Images)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# NCA Toolkit API Configuration
# Configure these settings to use the No-Code Architects Toolkit API
# for fast media processing (transcription, captioning, video editing, etc.)
# Documentation: https://github.com/stephengpope/no-code-architects-toolkit
# NCA Toolkit API Configuration (Optional - for comparison with Whisper)
NCA_API_URL = os.environ.get('NCA_API_URL', 'http://localhost:8080')  # Base URL of NCA Toolkit API
NCA_API_KEY = os.environ.get('NCA_API_KEY', 'my_secret_key_123')  # API key for authentication (matches Docker container)
NCA_API_TIMEOUT = int(os.environ.get('NCA_API_TIMEOUT', '600'))  # Request timeout in seconds (10 minutes)
# Enable NCA API by default if running locally (can be overridden via environment variable)
NCA_API_ENABLED = os.environ.get('NCA_API_ENABLED', 'true').lower() == 'true'  # Enable/disable NCA API

# If NCA_API_ENABLED is False, will fallback to local processing (Whisper, ffmpeg)

# Whisper Transcription Configuration (Primary method)
WHISPER_MODEL_SIZE = os.environ.get('WHISPER_MODEL_SIZE', 'base')  # tiny, base, small, medium, large
# Model size recommendations:
#   - tiny: Fastest, least accurate (~1GB RAM, ~32x realtime)
#   - base: Good balance (~1GB RAM, ~16x realtime) - RECOMMENDED
#   - small: Better accuracy (~2GB RAM, ~6x realtime)
#   - medium: High accuracy (~5GB RAM, ~2x realtime)
#   - large: Best accuracy (~10GB RAM, ~1x realtime)

WHISPER_DEVICE = os.environ.get('WHISPER_DEVICE', 'cpu')  # 'cpu' or 'cuda' (GPU)
WHISPER_CONFIDENCE_THRESHOLD = float(os.environ.get('WHISPER_CONFIDENCE_THRESHOLD', '-1.5'))  # Confidence threshold for retry
WHISPER_RETRY_WITH_LARGER_MODEL = os.environ.get('WHISPER_RETRY_WITH_LARGER_MODEL', 'true').lower() == 'true'  # Auto-retry low confidence segments
WHISPERX_ENABLED = os.environ.get('WHISPERX_ENABLED', 'false').lower() == 'true'  # Enable WhisperX for better alignment/diarization

# Dual Transcription Mode (for comparison)
DUAL_TRANSCRIPTION_ENABLED = os.environ.get('DUAL_TRANSCRIPTION_ENABLED', 'true').lower() == 'true'  # Run both NCA and Whisper

# Jazzmin Settings
JAZZMIN_SETTINGS = {
    "site_title": "RedNote Admin",
    "site_header": "RedNote Manager",
    "site_brand": "RedNote Saver",
    "welcome_sign": "Welcome to RedNote Manager",
    "copyright": "RedNote Saver Ltd",
    "search_model": ["downloader.VideoDownload"],
    
    # Hide the default user/group management
    "hide_apps": ["auth"],
    
    # UI Customization
    "topmenu_links": [
        {"name": "Home",  "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "View Site", "url": "/", "new_window": True},
    ],
    "show_ui_builder": False,
    
    "icons": {
        "downloader.VideoDownload": "fas fa-video",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    
    "changeform_format": "horizontal_tabs",
    "override_admin_login": True,
    "custom_css": "downloader/admin_custom.css",
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-danger",
    "accent": "accent-danger",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-danger",
    "sidebar_nav_small_text": False,
    "theme": "darkly",  # Dark theme
    "dark_mode_theme": "darkly",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}

# Django REST Framework Settings
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [],  # Disable session auth to avoid CSRF for API
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
}

# CORS Settings - Allow React frontend
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5173",  # Vite default port
    "http://127.0.0.1:5173",
]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]
