# Generated by Django 4.2.26 on 2025-11-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0005_videodownload_transcript_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodownload',
            name='transcript_error_message',
            field=models.TextField(blank=True, help_text='Transcription error message if failed'),
        ),
        migrations.AddField(
            model_name='videodownload',
            name='transcription_status',
            field=models.CharField(choices=[('not_transcribed', 'Not Transcribed'), ('transcribing', 'Transcribing'), ('transcribed', 'Transcribed'), ('failed', 'Failed')], default='not_transcribed', help_text='Transcription status', max_length=20),
        ),
    ]
