# Generated by Django 4.2.26 on 2025-11-27 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0018_add_voice_removed_and_final_video_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodownload',
            name='transcript_without_timestamps',
            field=models.TextField(blank=True, help_text='Full transcript of video speech/audio WITHOUT timestamps (plain text)'),
        ),
        migrations.AlterField(
            model_name='videodownload',
            name='transcript',
            field=models.TextField(blank=True, help_text='Full transcript of video speech/audio WITH timestamps (00:00:00 format)'),
        ),
        migrations.AlterField(
            model_name='videodownload',
            name='transcript_hindi',
            field=models.TextField(blank=True, help_text='Hindi translation of the transcript (without timestamps)'),
        ),
    ]
