# Generated by Django 4.2.26 on 2025-11-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0025_update_watermark_to_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodownload',
            name='final_video_error',
            field=models.TextField(blank=True, help_text='Final video assembly error message if failed'),
        ),
        migrations.AddField(
            model_name='videodownload',
            name='final_video_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('removing_audio', 'Removing Audio'), ('combining_audio', 'Combining Audio'), ('completed', 'Completed'), ('failed', 'Failed')], default='not_started', help_text='Final video assembly status', max_length=20),
        ),
        migrations.AddField(
            model_name='videodownload',
            name='synthesized_at',
            field=models.DateTimeField(blank=True, help_text='When audio synthesis completed', null=True),
        ),
    ]
