# Generated by Django 4.2.26 on 2025-11-30 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0026_videodownload_final_video_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodownload',
            name='script_edited',
            field=models.BooleanField(default=False, help_text='Whether script was manually edited by user'),
        ),
        migrations.AddField(
            model_name='videodownload',
            name='script_edited_at',
            field=models.DateTimeField(blank=True, help_text='When script was last edited', null=True),
        ),
    ]
