# Generated by Django 4.2.26 on 2025-11-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0022_add_cloudinary_google_sheets'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatermarkSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Enable watermark on videos')),
                ('watermark_image', models.ImageField(blank=True, help_text='Watermark image file (PNG with transparency recommended)', null=True, upload_to='watermarks/')),
                ('position_change_interval', models.FloatField(default=1.0, help_text='Position change interval in seconds (how often watermark moves)')),
                ('opacity', models.FloatField(default=0.7, help_text='Watermark opacity (0.0 to 1.0)')),
                ('size_percentage', models.FloatField(default=10.0, help_text='Watermark size as percentage of video width (0-100)')),
            ],
            options={
                'verbose_name': 'Watermark Setting',
                'verbose_name_plural': 'Watermark Settings',
            },
        ),
    ]
