# Generated by Django 4.2.26 on 2025-11-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0025_update_watermark_to_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiprovidersettings',
            name='anthropic_api_key',
            field=models.CharField(blank=True, help_text='Anthropic API Key (Claude models)', max_length=255),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='default_provider',
            field=models.CharField(choices=[('gemini', 'Google Gemini'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic (Claude)')], default='gemini', help_text='Default AI provider for general tasks (enhancement, TTS markup, etc.)', max_length=50),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='gemini_api_key',
            field=models.CharField(blank=True, help_text='Google Gemini API Key (for TTS, enhancement, etc.)', max_length=255),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='openai_api_key',
            field=models.CharField(blank=True, help_text='OpenAI API Key (GPT models)', max_length=255),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='script_generation_provider',
            field=models.CharField(choices=[('gemini', 'Google Gemini'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic (Claude)')], default='gemini', help_text='AI provider for Hindi script generation', max_length=50),
        ),
        migrations.AlterField(
            model_name='aiprovidersettings',
            name='api_key',
            field=models.CharField(blank=True, help_text='[DEPRECATED] Use provider-specific API keys instead', max_length=255),
        ),
        migrations.AlterField(
            model_name='aiprovidersettings',
            name='provider',
            field=models.CharField(choices=[('gemini', 'Google Gemini'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic (Claude)')], default='gemini', help_text='[DEPRECATED] Use script_generation_provider or default_provider instead', max_length=50),
        ),
    ]
