# Generated by Django 4.2.26 on 2025-11-23 12:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0010_videodownload_audio_generation_prompt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the voice profile', max_length=100)),
                ('reference_audio', models.FileField(help_text='Reference audio file (.wav)', upload_to='voice_refs/')),
                ('reference_text', models.TextField(help_text='Transcript of the reference audio')),
                ('embedding_path', models.CharField(blank=True, help_text='Path to cached embedding file', max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='videodownload',
            name='synthesis_error',
            field=models.TextField(blank=True, help_text='Synthesis error message if failed'),
        ),
        migrations.AddField(
            model_name='videodownload',
            name='synthesis_status',
            field=models.CharField(choices=[('not_synthesized', 'Not Synthesized'), ('synthesizing', 'Synthesizing'), ('synthesized', 'Synthesized'), ('failed', 'Failed')], default='not_synthesized', help_text='Audio synthesis status', max_length=20),
        ),
        migrations.AddField(
            model_name='videodownload',
            name='synthesized_audio',
            field=models.FileField(blank=True, help_text='Synthesized audio file', null=True, upload_to='synthesized_audio/'),
        ),
        migrations.AddField(
            model_name='videodownload',
            name='voice_profile',
            field=models.ForeignKey(blank=True, help_text='Voice profile for audio synthesis', null=True, on_delete=django.db.models.deletion.SET_NULL, to='downloader.voiceprofile'),
        ),
    ]
