# Generated by Django 4.2.26 on 2025-11-23 06:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='Original Xiaohongshu URL', max_length=500)),
                ('title', models.CharField(blank=True, help_text='Video title', max_length=500)),
                ('video_url', models.URLField(blank=True, help_text='Extracted video URL', max_length=1000)),
                ('cover_url', models.URLField(blank=True, help_text='Cover/thumbnail URL', max_length=1000)),
                ('extraction_method', models.CharField(blank=True, choices=[('seekin', 'Seekin API'), ('yt-dlp', 'yt-dlp'), ('requests', 'Direct Requests')], help_text='Which extraction method succeeded', max_length=20)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', help_text='Download status', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if failed')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the download was requested')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update time')),
            ],
            options={
                'verbose_name': 'Video Download',
                'verbose_name_plural': 'Video Downloads',
                'ordering': ['-created_at'],
            },
        ),
    ]
