# Generated by Django 4.2.26 on 2025-12-02 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodownload',
            name='extracted_frames_paths',
            field=models.JSONField(blank=True, help_text='Array of extracted frame file paths stored in media/visual_frames/{video_id}/', null=True),
        ),
        migrations.AddField(
            model_name='videodownload',
            name='frames_extracted',
            field=models.BooleanField(default=False, help_text='Whether frames have been extracted from video'),
        ),
        migrations.AddField(
            model_name='videodownload',
            name='frames_extracted_at',
            field=models.DateTimeField(blank=True, help_text='When frames were extracted from video', null=True),
        ),
        migrations.AddField(
            model_name='videodownload',
            name='frames_extraction_interval',
            field=models.FloatField(blank=True, help_text='Interval in seconds between extracted frames (e.g., 1.0 for 1 frame per second)', null=True),
        ),
        migrations.AddField(
            model_name='videodownload',
            name='total_frames_extracted',
            field=models.IntegerField(default=0, help_text='Total number of frames extracted'),
        ),
    ]
