# Generated by Django 4.2.26 on 2025-11-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0002_videodownload_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodownload',
            name='video_id',
            field=models.CharField(blank=True, help_text='Unique Video ID from XHS', max_length=100, null=True, unique=True),
        ),
    ]
