# Generated by Django 4.2.26 on 2025-11-23 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0003_alter_videodownload_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodownload',
            name='ai_error_message',
            field=models.TextField(blank=True, help_text='AI processing error message if failed'),
        ),
        migrations.AddField(
            model_name='videodownload',
            name='ai_processed_at',
            field=models.DateTimeField(blank=True, help_text='When AI processing was completed', null=True),
        ),
        migrations.AddField(
            model_name='videodownload',
            name='ai_processing_status',
            field=models.CharField(choices=[('not_processed', 'Not Processed'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='not_processed', help_text='AI processing status', max_length=20),
        ),
        migrations.AddField(
            model_name='videodownload',
            name='ai_summary',
            field=models.TextField(blank=True, help_text='AI-generated summary or analysis'),
        ),
        migrations.AddField(
            model_name='videodownload',
            name='ai_tags',
            field=models.CharField(blank=True, help_text='AI-generated tags (comma-separated)', max_length=500),
        ),
    ]
