# Generated by Django 4.2.26 on 2025-11-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0004_videodownload_ai_error_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodownload',
            name='transcript',
            field=models.TextField(blank=True, help_text='Full transcript of video speech/audio'),
        ),
        migrations.AddField(
            model_name='videodownload',
            name='transcript_language',
            field=models.CharField(blank=True, help_text='Detected language of transcript', max_length=10),
        ),
        migrations.AddField(
            model_name='videodownload',
            name='transcript_processed_at',
            field=models.DateTimeField(blank=True, help_text='When transcription was completed', null=True),
        ),
    ]
