# Generated by Django 4.2.26 on 2025-11-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0007_videodownload_transcript_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodownload',
            name='transcript_hindi',
            field=models.TextField(blank=True, help_text='Hindi translation of the transcript'),
        ),
    ]
