# Generated by Django 4.2.26 on 2025-11-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0009_aiprovidersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodownload',
            name='audio_generation_prompt',
            field=models.TextField(blank=True, help_text='AI-generated prompt for audio generation'),
        ),
        migrations.AddField(
            model_name='videodownload',
            name='audio_prompt_error',
            field=models.TextField(blank=True, help_text='Audio prompt generation error message if failed'),
        ),
        migrations.AddField(
            model_name='videodownload',
            name='audio_prompt_generated_at',
            field=models.DateTimeField(blank=True, help_text='When audio prompt was generated', null=True),
        ),
        migrations.AddField(
            model_name='videodownload',
            name='audio_prompt_status',
            field=models.CharField(choices=[('not_generated', 'Not Generated'), ('generating', 'Generating'), ('generated', 'Generated'), ('failed', 'Failed')], default='not_generated', help_text='Audio prompt generation status', max_length=20),
        ),
    ]
