# Generated by Django 4.2.26 on 2025-11-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0010_videodownload_audio_generation_prompt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedVoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='voices/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
