# Generated by Django 4.2.26 on 2025-11-29 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0011_savedvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodownload',
            name='duration',
            field=models.IntegerField(default=0, help_text='Video duration in seconds'),
        ),
    ]
