# Generated by Django 4.2.26 on 2025-11-28 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0002_add_whisper_transcription_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodownload',
            name='has_audio',
            field=models.BooleanField(default=True, help_text='Whether video contains audio track'),
        ),
        migrations.AddField(
            model_name='videodownload',
            name='visual_transcript',
            field=models.TextField(blank=True, help_text='Visual: Frame-by-frame description WITH timestamps (HH:MM:SS format)'),
        ),
        migrations.AddField(
            model_name='videodownload',
            name='visual_transcript_hindi',
            field=models.TextField(blank=True, help_text='Visual: Hindi translation of visual description'),
        ),
        migrations.AddField(
            model_name='videodownload',
            name='visual_transcript_segments',
            field=models.JSONField(blank=True, help_text='Visual: Raw segments with timestamps and descriptions', null=True),
        ),
        migrations.AddField(
            model_name='videodownload',
            name='visual_transcript_without_timestamps',
            field=models.TextField(blank=True, help_text='Visual: Frame-by-frame description WITHOUT timestamps (plain text)'),
        ),
    ]
