# Generated by Django 4.2.26 on 2025-11-24 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0012_clonedvoice_alter_aiprovidersettings_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodownload',
            name='synthesis_error',
            field=models.TextField(blank=True, help_text='Synthesis error message if failed'),
        ),
        migrations.AddField(
            model_name='videodownload',
            name='synthesis_status',
            field=models.CharField(choices=[('not_synthesized', 'Not Synthesized'), ('synthesizing', 'Synthesizing'), ('synthesized', 'Synthesized'), ('failed', 'Failed')], default='not_synthesized', help_text='Audio synthesis status', max_length=20),
        ),
        migrations.AddField(
            model_name='videodownload',
            name='synthesized_audio',
            field=models.FileField(blank=True, help_text='Synthesized audio file', null=True, upload_to='synthesized_audio/'),
        ),
        migrations.AddField(
            model_name='videodownload',
            name='voice_profile',
            field=models.ForeignKey(blank=True, help_text='Voice profile used for synthesis', null=True, on_delete=django.db.models.deletion.SET_NULL, to='downloader.clonedvoice'),
        ),
    ]
