# Generated by Django 4.2.26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0013_videodownload_synthesis_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodownload',
            name='duration',
            field=models.FloatField(blank=True, help_text='Video duration in seconds', null=True),
        ),
        migrations.AddField(
            model_name='videodownload',
            name='hindi_script',
            field=models.TextField(blank=True, help_text='AI-generated Hindi script for TTS'),
        ),
        migrations.AddField(
            model_name='videodownload',
            name='script_error_message',
            field=models.TextField(blank=True, help_text='Script generation error message if failed'),
        ),
        migrations.AddField(
            model_name='videodownload',
            name='script_generated_at',
            field=models.DateTimeField(blank=True, help_text='When script was generated', null=True),
        ),
        migrations.AddField(
            model_name='videodownload',
            name='script_status',
            field=models.CharField(choices=[('not_generated', 'Not Generated'), ('generating', 'Generating'), ('generated', 'Generated'), ('failed', 'Failed')], default='not_generated', help_text='Hindi script generation status', max_length=20),
        ),
        migrations.AddField(
            model_name='videodownload',
            name='tts_repetition_penalty',
            field=models.FloatField(default=5.0, help_text='TTS repetition penalty'),
        ),
        migrations.AddField(
            model_name='videodownload',
            name='tts_speed',
            field=models.FloatField(default=1.0, help_text='TTS speed multiplier (calculated from duration)'),
        ),
        migrations.AddField(
            model_name='videodownload',
            name='tts_temperature',
            field=models.FloatField(default=0.75, help_text='TTS temperature parameter'),
        ),
    ]






