# Generated by Django 4.2.26 on 2025-11-27 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0014_videodownload_duration_and_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodownload',
            name='video_source',
            field=models.CharField(choices=[('rednote', 'RedNote/Xiaohongshu'), ('youtube', 'YouTube'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('vimeo', 'Vimeo'), ('local', 'Local Upload'), ('other', 'Other')], default='rednote', help_text='Video source/platform', max_length=20),
        ),
        migrations.AlterField(
            model_name='videodownload',
            name='extraction_method',
            field=models.CharField(blank=True, choices=[('seekin', 'Seekin API'), ('yt-dlp', 'yt-dlp'), ('requests', 'Direct Requests'), ('local', 'Local Upload')], help_text='Which extraction method succeeded', max_length=20),
        ),
        migrations.AlterField(
            model_name='videodownload',
            name='url',
            field=models.URLField(blank=True, help_text='Original video URL (optional for local uploads)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='videodownload',
            name='video_id',
            field=models.CharField(blank=True, help_text='Unique Video ID', max_length=100, null=True, unique=True),
        ),
    ]
