# Generated by Django 4.2.26 on 2025-11-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0016_add_final_processed_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodownload',
            name='voice_removed_video_url',
            field=models.URLField(blank=True, help_text='2. Video URL after removing original audio (no audio)', max_length=1000),
        ),
        migrations.AlterField(
            model_name='videodownload',
            name='final_processed_video_url',
            field=models.URLField(blank=True, help_text='3. Final video URL after TTS audio replacement (with new Hindi audio)', max_length=1000),
        ),
        migrations.AlterField(
            model_name='videodownload',
            name='local_file',
            field=models.FileField(blank=True, help_text='1. Downloaded video file (original with audio)', null=True, upload_to='videos/'),
        ),
    ]
