# Generated by Django 4.2.26 on 2025-11-27 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0017_add_voice_removed_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodownload',
            name='final_processed_video',
            field=models.FileField(blank=True, help_text='3. Final video file after TTS audio replacement (with new Hindi audio)', null=True, upload_to='videos/final/'),
        ),
        migrations.AddField(
            model_name='videodownload',
            name='voice_removed_video',
            field=models.FileField(blank=True, help_text='2. Video file after removing original audio (no audio)', null=True, upload_to='videos/voice_removed/'),
        ),
    ]
