# Generated by Django 4.2.26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0003_add_visual_transcript_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodownload',
            name='enhanced_transcript',
            field=models.TextField(blank=True, help_text='Enhanced: AI-merged transcript WITH timestamps (HH:MM:SS format) - combines Whisper, NCA, and Visual'),
        ),
        migrations.AddField(
            model_name='videodownload',
            name='enhanced_transcript_hindi',
            field=models.TextField(blank=True, help_text='Enhanced: Hindi translation of enhanced transcript'),
        ),
        migrations.AddField(
            model_name='videodownload',
            name='enhanced_transcript_segments',
            field=models.JSONField(blank=True, help_text='Enhanced: Raw segments with timestamps from AI enhancement', null=True),
        ),
        migrations.AddField(
            model_name='videodownload',
            name='enhanced_transcript_without_timestamps',
            field=models.TextField(blank=True, help_text='Enhanced: AI-merged transcript WITHOUT timestamps (plain text)'),
        ),
    ]

