# Generated by Django 4.2.26 on 2025-11-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0024_add_watermark_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watermarksettings',
            name='size_percentage',
        ),
        migrations.RemoveField(
            model_name='watermarksettings',
            name='watermark_image',
        ),
        migrations.AddField(
            model_name='watermarksettings',
            name='font_color',
            field=models.CharField(default='white', help_text="Font color (e.g., 'white', 'black', '#FFFFFF')", max_length=20),
        ),
        migrations.AddField(
            model_name='watermarksettings',
            name='font_size',
            field=models.IntegerField(default=24, help_text='Font size for watermark text'),
        ),
        migrations.AddField(
            model_name='watermarksettings',
            name='watermark_text',
            field=models.CharField(blank=True, default='', help_text='Watermark text to display on videos', max_length=100),
        ),
    ]
