# Generated by Django 4.2.26 on 2025-11-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodownload',
            name='description',
            field=models.TextField(blank=True, help_text='English Description (Translated)'),
        ),
        migrations.AddField(
            model_name='videodownload',
            name='is_downloaded',
            field=models.BooleanField(default=False, help_text='Is video saved locally?'),
        ),
        migrations.AddField(
            model_name='videodownload',
            name='local_file',
            field=models.FileField(blank=True, help_text='Locally downloaded video file', null=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='videodownload',
            name='original_description',
            field=models.TextField(blank=True, help_text='Original Chinese Description'),
        ),
        migrations.AddField(
            model_name='videodownload',
            name='original_title',
            field=models.CharField(blank=True, help_text='Original Chinese Title', max_length=500),
        ),
        migrations.AddField(
            model_name='videodownload',
            name='video_id',
            field=models.CharField(blank=True, help_text='Unique Video ID from XHS', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='videodownload',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', help_text='Extraction status', max_length=20),
        ),
        migrations.AlterField(
            model_name='videodownload',
            name='title',
            field=models.CharField(blank=True, help_text='English Title (Translated)', max_length=500),
        ),
    ]
