# Generated by Django 4.2.26 on 2025-11-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0006_videodownload_transcript_error_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodownload',
            name='transcript_started_at',
            field=models.DateTimeField(blank=True, help_text='When transcription started', null=True),
        ),
    ]
