# Generated by Django 4.2.26 on 2025-11-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0008_add_hindi_translation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('gemini', 'Gemini'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic')], default='gemini', max_length=20)),
                ('api_key', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'AI Provider Setting',
                'verbose_name_plural': 'AI Provider Settings',
            },
        ),
    ]
