# Generated by Django 4.2.26 on 2025-11-23 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0010_videodownload_audio_generation_prompt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videodownload',
            name='audio_generation_prompt',
        ),
        migrations.RemoveField(
            model_name='videodownload',
            name='audio_prompt_error',
        ),
        migrations.RemoveField(
            model_name='videodownload',
            name='audio_prompt_generated_at',
        ),
        migrations.RemoveField(
            model_name='videodownload',
            name='audio_prompt_status',
        ),
    ]
