# Generated by Django 4.2.26 on 2025-11-24 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0011_remove_videodownload_audio_generation_prompt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClonedVoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='cloned_voices/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='aiprovidersettings',
            name='provider',
            field=models.CharField(choices=[('gemini', 'Gemini'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic')], default='gemini', max_length=50),
        ),
    ]
