# Generated by Django 4.2.26 on 2025-11-27 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0015_add_video_source_and_local_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodownload',
            name='final_processed_video_url',
            field=models.URLField(blank=True, help_text='Final video URL after TTS audio replacement', max_length=1000),
        ),
    ]
