# Generated by Django 4.2.26 on 2025-11-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0020_add_review_status_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clonedvoice',
            options={'ordering': ['-is_default', '-created_at']},
        ),
        migrations.AddField(
            model_name='clonedvoice',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Default voice used for video TTS generation'),
        ),
    ]
